---
sidebar: sidebar 
permalink: docs/concept_hcc_expandoverview.html 
summary: 您可以使用 NetApp 混合云控制扩展 NetApp HCI 系统。 
keywords: NetApp, HCI, on premise, expand, hcc, hybrid cloud control 
---
= 扩展概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用 NetApp 混合云控制扩展 NetApp HCI 系统。您可以单独扩展存储或计算资源，也可以同时扩展这些资源。


NOTE: 根据存储集群的现有 Element 软件版本，新的和备用的 H610S 存储节点可能具有其他安装要求。有关详细信息，请联系 NetApp 支持部门。

在 NetApp HCI 机箱中安装节点后，您可以使用 NetApp 混合云控制将 NetApp HCI 配置为使用新资源。NetApp HCI 会检测现有网络配置，并在现有网络和 VLAN （如果有）中为您提供配置选项。


NOTE: 如果您最近扩展了安装，但新资产未自动添加到配置中，则可能需要手动添加这些资产。请参见 link:task_mnode_work_overview.html["管理节点概述"]。

如果 vSphere 集群中的计算节点使用不同的 CPU 版本，则 NetApp HCI 会使用 VMware 增强型 vMotion 兼容性（ EVC ）来确保 vMotion 正常运行。如果扩展需要 EVC ， NetApp HCI 会尽可能自动启用它。

在以下情况下，您可能需要在 vSphere 客户端中手动更改 EVC 设置才能完成扩展：

* 现有计算节点的 CPU 版本比您要添加的计算节点更高。
* 控制 vCenter 实例不支持所需的 EVC 级别。
* 您尝试添加的计算节点的 CPU 版本比控制 vCenter 实例的 EVC 设置更早。



NOTE: 在 NetApp 部署引擎中扩展 NetApp HCI 计算或存储资源时，您应连接到管理现有 NetApp HCI 计算节点的 vCenter 实例。



== 了解更多信息

* link:task_hcc_expand_compute.html["展开 NetApp HCI 计算资源"]
* link:task_hcc_expand_storage.html["展开 NetApp HCI 存储资源"]
* link:task_hcc_expand_compute_and_storage.html["同时扩展 NetApp HCI 存储和计算资源"]
* https://docs.netapp.com/us-en/vcp/index.html["适用于 vCenter Server 的 NetApp Element 插件"^]

