---
sidebar: sidebar 
permalink: docs/concept_hci_clusters.html 
summary: 集群由一组存储节点组成。一个 NetApp HCI 存储集群至少需要有两个存储节点。集群在网络上显示为一个逻辑组，然后可作为块存储访问。 
keywords: netapp, hci, storage nodes, clusters, two-node cluster, three-node cluster, 2-node cluster, 3-node cluster 
---
= 集群
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
集群是一组节点，作为一个整体运行，用于提供存储或计算资源。从 NetApp HCI 1.8 开始，您可以拥有一个包含两个节点的存储集群。存储集群在网络上显示为一个逻辑组，然后可作为块存储访问。

NetApp HCI 中的存储层由 NetApp Element 软件提供，管理层由适用于 vCenter Server 的 NetApp Element 插件提供。存储节点是指包含一组驱动器的服务器，这些驱动器通过绑定 10G 网络接口相互通信。每个存储节点都连接到两个网络：存储和管理，每个网络都有两个独立的链路，用于实现冗余和性能。每个节点在每个网络上都需要一个 IP 地址。您可以使用新的存储节点创建集群，也可以向现有集群添加存储节点以提高存储容量和性能。



== 权威存储集群

权威存储集群是 NetApp Hybrid Cloud Control 用于对用户进行身份验证的存储集群。

如果您的管理节点只有一个存储集群，则它是权威集群。如果您的管理节点有两个或更多存储集群，其中一个集群将被分配为权威集群，只有该集群中的用户才能登录到 NetApp Hybrid Cloud Control 。要了解哪个集群是权威集群，您可以使用 `get /mnode/about` API 。在响应中， `token_url` 字段中的 IP 地址是权威存储集群的管理虚拟 IP 地址（ MVIP ）。如果您尝试以非权威集群上的用户身份登录到 NetApp Hybrid Cloud Control ，则登录尝试将失败。

许多 NetApp Hybrid Cloud Control 功能都设计用于多个存储集群，但身份验证和授权存在限制。身份验证和授权的限制是，权威集群中的用户可以对与 NetApp Hybrid Cloud Control 关联的其他集群执行操作，即使他们不是其他存储集群上的用户也是如此。在继续管理多个存储集群之前，您应确保在权威集群上定义的用户已在具有相同权限的所有其他存储集群上定义。

您可以使用 NetApp Hybrid Cloud Control 管理用户。

在继续管理多个存储集群之前，您应确保在权威集群上定义的用户已在具有相同权限的所有其他存储集群上定义。请参见 link:task_mnode_manage_storage_cluster_assets.html["创建和管理存储集群资产"] 有关使用管理节点存储集群资产的详细信息，请参见。



== 孤立容量

如果新添加的节点占用的集群总容量超过 50% ，则此节点的某些容量将变为不可用（ " 孤立 " ），以使其符合容量规则。在添加更多存储容量之前，情况始终如此。如果添加的节点非常大，并且也不遵守容量规则，则先前的孤立节点将不再处于孤立状态，而新添加的节点将变为孤立状态。应始终成对添加容量，以免发生这种情况。当节点变为孤立时，会引发相应的集群故障。



== 双节点存储集群

从 NetApp HCI 1.8 开始，您可以设置一个包含两个存储节点的存储集群。

* 您可以使用某些类型的节点来构成双节点存储集群。请参见 https://library.netapp.com/ecm/ecm_download_file/ECMLP2865021["NetApp HCI 1.8 发行说明"^]。
+

NOTE: 在双节点集群中，存储节点仅限于具有 480 GB 和 960 GB 驱动器的节点，并且节点的型号类型必须相同。

* 双节点存储集群最适合工作负载不依赖于大容量和高性能要求的小型部署。
* 除了两个存储节点之外，一个双节点存储集群还包括两个 * NetApp HCI 见证节点 * 。
+

NOTE: 了解更多信息 link:concept_hci_nodes.html["见证节点。"]

* 您可以将双节点存储集群扩展为三节点存储集群。三节点集群可通过提供从存储节点故障中自动修复的功能来提高故障恢复能力。
* 双节点存储集群提供的安全特性和功能与传统的四节点存储集群相同。
* 双节点存储集群与四节点存储集群使用相同的网络。网络可在 NetApp HCI 部署期间使用 NetApp 部署引擎向导进行设置。




=== 存储集群仲裁

Element 软件会从选定节点创建存储集群，从而维护已复制的集群配置数据库。要保持集群故障恢复能力所需的仲裁，至少需要三个节点才能加入集群集合。双节点集群中的见证节点用于确保有足够的存储节点来构成有效的集合仲裁。要创建集合，存储节点优先于见证节点。对于涉及双节点存储集群的最少三节点集合，使用两个存储节点和一个见证节点。


TIP: 在具有两个存储节点和一个见证节点的三节点集合中，如果一个存储节点脱机，则集群将进入降级状态。在两个见证节点中，只有一个节点可以在集合中处于活动状态。无法将第二个见证节点添加到集合中，因为它会执行备份角色。集群将保持降级状态，直到脱机存储节点恢复联机状态或替代节点加入集群为止。

如果见证节点发生故障，则其余见证节点将加入此集合，以形成一个三节点集合。您可以部署一个新的见证节点来替换出现故障的见证节点。



=== 双节点存储集群中的自动修复和故障处理

如果传统集群中某个节点上的硬件组件发生故障，则集群可以重新平衡该组件上发生故障的数据，并将这些数据重新分配给集群中的其他可用节点。在双节点存储集群中，此自动修复功能不可用，因为集群必须至少有三个物理存储节点可用于自动修复。当双节点集群中的一个节点发生故障时，双节点集群不需要重新生成第二个数据副本。系统会为剩余活动存储节点中的块数据复制新写入。更换故障节点并加入集群后，两个物理存储节点之间的数据将重新平衡。



== 包含三个或更多节点的存储集群

将两个存储节点扩展到三个存储节点可以在发生节点和驱动器故障时自动修复，从而提高集群的故障恢复能力，但不会提供额外容量。您可以使用扩展 link:task_hcc_expand_storage.html["NetApp Hybrid Cloud Control UI"]。从双节点集群扩展到三节点集群时，容量可能会处于孤立状态（请参见 <<孤立容量>>）。在安装之前， UI 向导会显示有关孤立容量的警告。在存储节点发生故障时，仍可使用一个见证节点来保持集合仲裁，而另一个见证节点处于备用状态。将三节点存储集群扩展为四节点集群时，容量和性能将会提高。在四节点集群中，不再需要见证节点来构成集群仲裁。您可以扩展到多达 64 个计算节点和 40 个存储节点。



== 了解更多信息

* https://www.netapp.com/pdf.html?item=/media/9489-tr-4823.pdf["NetApp HCI 双节点存储集群 | TR-4823"^]
* https://docs.netapp.com/us-en/vcp/index.html["适用于 vCenter Server 的 NetApp Element 插件"^]
* http://docs.netapp.com/sfe-122/index.jsp["SolidFire 和 Element 软件文档中心"^]

