---
sidebar: sidebar 
permalink: docs/hci_prereqs_network_switch.html 
summary: 了解此版本的 NetApp HCI 中的新增功能。 
keywords: netapp, hci, network, switch, requirements 
---
= 网络和交换机要求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: netapp, hci, network, switch, requirements


[role="lead"]
要确保成功部署 NetApp HCI 所使用的交换机，需要进行特定配置。有关在您的环境中实施以下每个要求的具体说明，请参见交换机文档。

NetApp HCI 部署至少需要三个网段，以下每种类型的流量对应一个网段：

* 管理
* VMware vMotion
* 存储 / 数据


根据 NetApp H 系列计算和存储节点型号以及规划的布线配置，您可以使用不同的交换机以物理方式分隔这些网络，也可以使用 VLAN 以逻辑方式分隔这些网络。但是，对于大多数部署，您需要使用 VLAN 在逻辑上隔离这些网络（以及任何其他额外的虚拟机网络）。

计算和存储节点需要能够在部署之前，部署期间和部署之后进行通信。如果要为存储和计算节点实施单独的管理网络，请确保这些管理网络之间具有网络路由。这些网络必须已分配网关，并且这些网关之间必须有路由。确保为每个新节点分配了一个网关，以便于节点和管理网络之间进行通信。

NetApp HCI 具有以下交换机要求：

* 连接到 NetApp HCI 节点的所有交换机端口都必须配置为生成树边缘端口。
+
** 在 Cisco 交换机上，根据交换机型号，软件版本和端口类型，您可以使用以下命令之一执行此操作：
+
*** `sPing-tree 端口类型 edge`
*** `sPing-tree 端口类型 Edge trunk`
*** `sping-tree portfast`
*** `sping-tree portfast trunk`


** 在 Mellanox 交换机上，您可以使用 `spaning-tree port type edge` 命令执行此操作。


* 除了带外管理之外， NetApp HCI 节点具有用于所有网络功能的冗余端口。为了获得最佳的故障恢复能力，请将这些端口划分到两个交换机上，并通过冗余上行链路连接到传统分层架构或第 2 层主干叶架构。
* 处理存储，虚拟机和 vMotion 流量的交换机必须支持每个端口至少 10GbE 的速度（每个端口最多支持 25GbE ）。
* 处理管理流量的交换机必须支持每个端口至少 1GbE 的速度。
* 您必须在处理存储和 vMotion 流量的交换机端口上配置巨型帧。主机必须能够端到端发送 9000 字节数据包，才能成功安装。
* 您必须将管理网络交换机端口配置为允许为每个主机上的管理 NIC 端口配置任何大小的 MTU 。例如，如果主机管理网络端口使用的 MTU 大小为 1 ， 50 字节，则必须将管理网络交换机端口配置为至少允许 1 ， 50 字节的 MTU （管理网络不需要 9000 字节的 MTU ）。MTU 设置应始终保持一致
* 所有存储和计算节点之间的往返网络延迟不应超过 2 毫秒。


所有 NetApp HCI 节点均可通过专用管理端口提供额外的带外管理功能。NetApp H300S ， H300E ， H500S ， H500E ， H700S ， H700E 和 H410C 节点还支持通过端口 A 进行 IPMI 访问作为最佳实践，您应通过为环境中的所有节点配置带外管理来简化 NetApp HCI 的远程管理。

[discrete]
== 了解更多信息

* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI 资源页面"^]
* https://docs.netapp.com/us-en/vcp/index.html["适用于 vCenter Server 的 NetApp Element 插件"^]

