---
sidebar: sidebar 
permalink: docs/task_nde_access_manual_ip.html 
summary: 了解如何通过手动将 IP 地址分配给 NetApp HCI 节点来访问 NetApp 部署引擎。 
keywords: netapp, hci, netapp deployment engine, deployment, engine, deploy, access 
---
= 手动分配 IP 地址以访问 NetApp 部署引擎
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以手动为所有 NetApp HCI 节点上的绑定 1G 和绑定 10G 接口分配静态 IPv4 地址，以访问 NetApp 部署引擎和部署 NetApp HCI 。除非您的网络有特殊要求，否则不应使用此方法。

.您需要的内容
* 您或您的网络管理员已完成安装和设置说明文档中的任务。
* 您可以对 NetApp HCI 节点进行物理访问。
* 所有 NetApp HCI 节点均已启动。
* 未为 NetApp HCI 网络启用 DHCP ，并且 NetApp HCI 节点未从 DHCP 服务器获取 IP 地址。注意：在使用 NetApp 部署引擎部署系统之前手动分配的所有 IP 地址都是临时的，不能重复使用。如果您选择手动分配 IP 地址，则需要留出第二组未使用的永久 IP 地址，以便在最终部署期间分配这些地址。


.关于此任务
在此配置中，计算和存储节点将使用静态 IPv4 地址在部署期间发现其他节点并与其进行通信。不建议使用此配置。

.步骤
. 将 KVM 插入一个 NetApp HCI 存储节点的背面（此节点将成为控制存储节点）。
. 在用户界面中配置绑定 1G 和绑定 10G 的 IP 地址，子网掩码和网关地址。如果需要，您还可以为每个网络配置 VLAN ID 。
. 对其余存储和计算节点重复步骤 2 。
. 在可以访问 NetApp HCI 管理网络的计算机上打开 Web 浏览器。
. 浏览到分配给控制存储节点的绑定 1G IP 地址。例如：
+
[listing]
----
http://<Bond1G IP address>
----
+
此时将转到 NetApp 部署引擎用户界面。



[discrete]
== 了解更多信息

* link:firmware_driver_versions.html["NetApp HCI 支持的固件和ESXi驱动程序版本以及NetApp HCI 存储节点的固件版本"]

