---
sidebar: sidebar 
permalink: docs/task_nde_configure_credentials.html 
summary: 了解如何在 NetApp HCI 部署期间配置 VMware vSphere 。 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= 配置 NetApp HCI 凭据
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在部署期间，您可以定义一组凭据，以便在新部署的 VMware vSphere 环境， NetApp HCI 计算和存储资源以及管理节点中使用。如果要将 NetApp HCI 部署到现有 vSphere 环境中，则这些凭据不会应用于现有 vCenter Server 。

.关于此任务
有关您在 NetApp HCI 部署引擎中设置的凭据，请记住以下几点：

* * NetApp 混合云控制（ HCC ）或 Element UUI ：要在成功部署后登录到 NetApp HCC 或 Element 用户界面，请使用此部署步骤中指定的用户名和密码。
* * VMware vCenter * ：要登录到 vCenter （如果在部署过程中安装），请使用用户名以及后缀 `@vsphere.local` 或内置 `Administrator@vsphere.local` 用户帐户以及此部署步骤中指定的密码。
* * VMware ESXi* ：要登录到计算节点上的 ESXi ，请使用用户名 `root` 以及此部署步骤中指定的相同密码。


要与 VMware vCenter 实例交互， NetApp Hybrid Cloud Control 将使用以下选项之一：

* 在部署过程中安装的 vCenter 实例上的内置 `Administrator@vsphere.local` 用户帐户。
* 用于将 NetApp HCI 部署连接到现有 VMware vCenter Server 的 vCenter 凭据。


.步骤
. 在 * 凭据 * 页面的 * 用户名 * 字段中输入用户名。
. 在 * 密码 * 字段中输入密码。密码必须符合 * 密码必须包含 * 框中显示的密码条件。
. 在 * 重新输入密码 * 字段中确认密码。
. 单击 * 继续 * 。


[discrete]
== 了解更多信息

* link:firmware_driver_versions.html["NetApp HCI 支持的固件和ESXi驱动程序版本以及NetApp HCI 存储节点的固件版本"]
* 要稍后更新 vCenter 和 ESXi 凭据，请参见 link:task_hci_credentials_vcenter_esxi.html["更新 vCenter 或 ESXi 凭据"]。

