---
sidebar: sidebar 
permalink: docs/task_hcc_update_management_services.html 
summary: 在 NetApp HCI 系统升级过程中，您应更新管理服务。 
keywords: netapp, hci, on premise, cluster, management services 
---
= 更新管理服务
:allow-uri-read: 


[role="lead"]
安装管理节点 11.3 或更高版本后，您可以将管理服务更新到最新的捆绑包版本。

从 Element 11.3 管理节点版本开始，管理节点设计已根据提供单个服务的新模块化架构进行了更改。这些模块化服务可为 NetApp HCI 系统提供集中式和扩展式管理功能。管理服务包括系统遥测，日志记录和更新服务，适用于 vCenter Server 的 Element 插件的 QoSSIOC 服务， NetApp Hybrid Cloud Control 等。

.关于此任务
* 在升级 Element 软件之前，您必须升级到最新的管理服务包。



NOTE: 有关介绍每个服务包的主要服务，新功能，错误修复和解决方法的最新管理服务发行说明，请参见 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["管理服务发行说明"^]

从管理服务2.2开始、您必须先接受并保存最终用户许可协议(EULA)、然后才能使用NetApp Hybrid Cloud Control UI或API升级管理服务：

. 在Web浏览器中打开管理节点的IP地址：
+
[listing]
----
https://<ManagementNodeIP>
----
. 通过提供存储集群管理员凭据登录到 NetApp Hybrid Cloud Control 。
. 选择靠近接口右上角的 * 升级 * 。
. 此时将弹出EULA。向下滚动、选择*我接受当前更新和所有未来更新*、然后选择*保存*。
+

NOTE: 如果您接受EULA、则会在所有未来更新中记录此EULA、并启用自动下载功能。您将收到有关NetApp软件更新和升级的更新、您可以在方便时自行决定安装这些更新。您可以通过禁用与NetApp联机软件存储库的网络连接来禁用自动下载功能。



您可以使用 NetApp Hybrid Cloud Control UI 或管理节点 REST API 更新管理服务：

* <<Update management services using Hybrid Cloud Control>> （建议方法）
* <<Update management services using the management node API>>
* <<Update management services using the management node API for dark sites>>




== 使用 Hybrid Cloud Control 更新管理服务

您可以使用 NetApp Hybrid Cloud Control 更新 NetApp 管理服务。

管理服务捆绑包可为您的安装提供增强功能和修复，而不是主要版本。

.开始之前
* 您正在运行管理节点 11.3 或更高版本。
* 如果要将管理服务更新到版本 2.16 或更高版本，并且运行的是管理节点 11.3 到 11.8 ，则在更新管理服务之前，需要先增加管理节点 VM 的 RAM ：
+
.. 关闭管理节点虚拟机。
.. 将管理节点虚拟机的 RAM 从 12 GB 更改为 24 GB 。
.. 打开管理节点虚拟机的电源。


* 您的集群版本运行的是 NetApp Element 软件 11.3 或更高版本。
* 您已将管理服务至少升级到 2.1.326 版。NetApp Hybrid Cloud Control 升级在早期的服务捆绑包中不可用。



NOTE: 有关每个服务包版本的可用服务列表，请参见 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["管理服务发行说明"^]。

.步骤
. 在Web浏览器中打开管理节点的IP地址：
+
[listing]
----
https://<ManagementNodeIP>
----
. 通过提供存储集群管理员凭据登录到 NetApp Hybrid Cloud Control 。
. 选择靠近接口右上角的 * 升级 * 。
. 在 Upgrades 页面上，选择 * 管理服务 * 选项卡。
+
管理服务选项卡显示管理服务软件的当前版本和可用版本。

+

NOTE: 如果您的安装无法访问 Internet ，则仅会显示当前软件版本。如果您已建立外部连接，但 NetApp HCI 无法访问 NetApp 联机存储库，请检查您的 link:task_mnode_configure_proxy_server.html["代理配置："^]。

. 如果您的安装可以访问 Internet ，并且可以进行管理服务升级，请选择 * 开始升级 * 。
. 如果您的安装无法访问 Internet ，请执行以下操作：
+
.. 按照页面上的说明将管理服务升级包下载并保存到您的计算机。
.. 选择 * 浏览 * 以找到您保存的软件包并上传它。




升级开始后，您可以在此页面上查看升级状态。升级期间，您可能会与 NetApp Hybrid Cloud Control 断开连接，因此必须重新登录才能查看升级结果。



== 使用管理节点 API 更新管理服务

理想情况下，用户应从 NetApp Hybrid Cloud Control 执行管理服务更新。但是，您可以从管理节点使用 REST API UI 手动更新管理服务。

.开始之前
* 您正在运行管理节点 11.3 或更高版本。
* 如果要将管理服务更新到版本 2.16 或更高版本，并且运行的是管理节点 11.3 到 11.8 ，则在更新管理服务之前，需要先增加管理节点 VM 的 RAM ：
+
.. 关闭管理节点虚拟机。
.. 将管理节点虚拟机的 RAM 从 12 GB 更改为 24 GB 。
.. 打开管理节点虚拟机的电源。


* 您的集群版本运行的是 NetApp Element 软件 11.3 或更高版本。
* 您已将管理服务至少升级到 2.1.326 版。NetApp Hybrid Cloud Control 升级在早期的服务捆绑包中不可用。



NOTE: 有关每个服务包版本的可用服务列表，请参见 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["管理服务发行说明"^]。

.步骤
. 在管理节点上打开 REST API UI ： `https://<ManagementNodeIP>/mnode`
. 选择 * 授权 * 并完成以下操作：
+
.. 输入集群用户名和密码。
.. 如果尚未填充值，请将客户端 ID 输入为 `mnode-client` 。
.. 选择 * 授权 * 以开始会话。
.. 关闭窗口。


. （可选）确认管理节点服务的可用版本： `get /services/versions`
. （可选）获取有关最新版本的详细信息： `获取 /services/versions/latest`
. （可选）获取有关特定版本的详细信息： `GET /services/versions/ ｛ version ｝ /info`
. 执行以下管理服务更新选项之一：
+
.. 运行此命令可更新到最新版本的管理节点服务： `PUT /services/update/latest`
.. 运行此命令以更新到管理节点服务的特定版本： `PUT /services/update/ ｛ version ｝`


. 运行 `get/services/update/status` 以监控更新状态。
+
成功更新将返回类似于以下示例的结果：

+
[listing]
----
{
"current_version": "2.10.29",
"details": "Updated to version 2.14.60",
"status": "success"
}
----




== 使用非公开站点的管理节点 API 更新管理服务

理想情况下，用户应从 NetApp Hybrid Cloud Control 执行管理服务更新。但是，您可以使用 REST API 手动将管理服务的服务包更新上传到，提取并部署到管理节点。您可以从管理节点的 REST API UI 运行每个命令。

.开始之前
* 您已部署 NetApp Element 软件管理节点 11.3 或更高版本。
* 如果要将管理服务更新到版本 2.16 或更高版本，并且运行的是管理节点 11.3 到 11.8 ，则在更新管理服务之前，需要先增加管理节点 VM 的 RAM ：
+
.. 关闭管理节点虚拟机。
.. 将管理节点虚拟机的 RAM 从 12 GB 更改为 24 GB 。
.. 打开管理节点虚拟机的电源。


* 您的集群版本运行的是 NetApp Element 软件 11.3 或更高版本。
* 您已从下载服务包更新 https://mysupport.netapp.com/site/products/all/details/mgmtservices/downloads-tab["NetApp 支持站点"^] 可在非公开站点中使用的设备。


.步骤
. 在管理节点上打开 REST API UI ： `https://<ManagementNodeIP>/mnode`
. 选择 * 授权 * 并完成以下操作：
+
.. 输入集群用户名和密码。
.. 如果尚未填充值，请将客户端 ID 输入为 `mnode-client` 。
.. 选择 * 授权 * 以开始会话。
.. 关闭窗口。


. 使用以下命令在管理节点上上传并提取服务包： `PUT /services/upload`
. 在管理节点上部署管理服务： `PUT /services/Deploy`
. 监控更新状态： `get /services/update/status`
+
成功更新将返回类似于以下示例的结果：

+
[listing]
----
{
"current_version": "2.10.29",
"details": "Updated to version 2.17.52",
"status": "success"
}
----


[discrete]
== 了解更多信息

* https://docs.netapp.com/us-en/vcp/index.html["适用于 vCenter Server 的 NetApp Element 插件"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI 资源页面"^]

