---
sidebar: sidebar 
permalink: docs/task_nde_hci_power_off_storage.html 
summary: 了解如何关闭 NetApp HCI 计算节点。 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= 关闭 NetApp HCI 系统的存储资源
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
关闭 NetApp HCI 的存储资源时，您需要使用 `Shutdown` Element API 方法正确暂停存储节点。

.步骤
关闭计算资源后，您可以使用 Web 浏览器关闭 NetApp HCI 存储集群的所有节点。

. 登录到存储集群并验证是否已连接到正确的 MVIP 。
. (可选)验证主机的所有I/O操作是否已停止：
+
.. 对正在使用的一个或多个虚拟机管理程序使用适当的命令暂停主机端的I/O。
.. 在集群UI中、选择*报告*>*概述*。"集群输入/输出"图上不应有任何活动。
.. 在所有I/O操作停止后、请等待20分钟、然后再关闭集群。


. 验证 iSCSI 会话计数是否为零。
. 导航到 * 集群 > 节点 > 活动 * ，并记录集群中所有活动节点的节点 ID 。
. 要关闭NetApp HCI 存储集群、请打开Web浏览器并使用以下URL调用关闭并暂停操作步骤 、其中 `{MVIP}` 是NetApp HCI 存储系统和的管理IP地址 `nodes=[]` 阵列包含您在步骤4中记录的节点ID。例如：
+
[listing]
----
https://{MVIP}/json-rpc/1.0?method=Shutdown&nodes=[1,2,3,4]&option=halt
----
+

NOTE: 您可以在匿名窗口中运行此命令、以避免稍后从已保存的URL再次运行此命令。

. 输入集群管理员用户名和密码。
. 通过验证 `s所有存储集群节点是否包含在 API 结果的 " 成功` " 部分中，验证是否已成功返回 API 调用。
+
您已成功关闭所有 NetApp HCI 存储节点。

. 关闭浏览器或选项卡、以避免选择"返回"按钮并重复API调用。


[NOTE]
====
重新启动集群时、必须按照特定步骤验证所有节点是否均已联机：

. 验证所有严重严重性和 `volumesOffline` 集群故障已解决。
. 等待10到15分钟、以使集群建立连接。
. 启动主机以访问数据。


如果要在打开节点电源并在维护后验证其运行状况是否良好时留出更多时间、请联系技术支持以帮助延迟数据同步以防止不必要的箱同步。

====


== 了解更多信息

* link:firmware_driver_versions.html["NetApp HCI 支持的固件和ESXi驱动程序版本以及NetApp HCI 存储节点的固件版本"]

