---
sidebar: sidebar 
permalink: docs/task_hci_credentials_vcenter_esxi.html 
summary: 在 NetApp HCI 安装中，您可以更改由 NetApp 混合云控制管理的计算节点的 vCenter 和 ESXi 主机的凭据。 
keywords: netapp, hci, password, credential, vcenter, esxi, hybrid cloud control 
---
= 更新 vCenter 和 ESXi 凭据
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
要在 NetApp HCI 安装中保持 NetApp 混合云控制的全部功能，在 vCenter 和 ESXi 主机中更改凭据时，您还需要在管理节点上的资产服务中更新这些凭据。

.关于此任务
NetApp Hybrid Cloud Control 可与 vCenter 以及运行 VMware vSphere ESXi 的各个计算节点进行通信，以检索信息板的信息，并促进固件，软件和驱动程序的滚动升级。管理节点上的 NetApp Hybrid Cloud Control 及其相关服务使用凭据（用户名 / 密码）根据 VMware vCenter 和 ESXi 进行身份验证。

如果这些组件之间的通信失败，则在出现身份验证问题时， NetApp Hybrid Cloud Control 和 vCenter 将显示错误消息。如果 NetApp 混合云控制无法与 NetApp HCI 安装中关联的 VMware vCenter 实例进行通信，则它将显示红色错误横幅。由于 NetApp Hybrid Cloud Control 使用过时的凭据， VMware vCenter 将显示各个 ESXi 主机的 ESXi 帐户锁定消息。

NetApp HCI 中的管理节点使用以下名称引用这些组件：

* " 控制器资产 " 是指与您的 NetApp HCI 安装关联的 vCenter 实例。
* " 计算节点资产 " 是指 NetApp HCI 安装中的 ESXi 主机。


在使用 NetApp 部署引擎首次安装 NetApp HCI 期间，管理节点会将您为 vCenter 指定的管理用户的凭据和 ESXi 服务器上的 "root" 帐户密码存储在一起。



== 使用管理节点 REST API 更新 vCenter 密码

按照以下步骤更新控制器资产。请参见 link:task_mnode_edit_vcenter_assets.html["查看或编辑现有控制器资产"]。



== 使用管理节点 REST API 更新 ESXi 密码

.步骤
. 要大致了解管理节点 REST API 用户界面，请参见 link:task_mnode_work_overview_API.html["管理节点 REST API 用户界面概述"]。
. 访问管理节点上用于管理服务的 REST API UI ：
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
+
将 <management node IP> 替换为用于 NetApp HCI 的管理网络上管理节点的 IPv4 地址。

. 单击 * 授权 * 或任何锁定图标并完成以下操作：
+
.. 输入 NetApp SolidFire 集群管理用户名和密码。
.. 输入客户端 ID `mnode-client` 。
.. 单击 * 授权 * 开始会话。
.. 关闭窗口。


. 从 REST API UI 中，单击 * 获取​ /assets/compute_nodes* 。
+
此操作将检索存储在管理节点中的计算节点资产的记录。

+
以下是 UI 中指向此 API 的直接链接：

+
[listing]
----
https://<ManagementNodeIP>/mnode/#/assets/routes.v1.assets_api.get_compute_nodes
----
. 单击 * 试用 * 。
. 单击 * 执行 * 。
. 在响应正文中，确定需要更新凭据的计算节点资产记录。您可以使用 "IP" 和 "host_name " 属性查找正确的 ESXi 主机记录。
+
[listing]
----
"config": { },
"credentialid": <credential_id>,
"hardware_tag": <tag>,
"host_name": <host_name>,
"id": <id>,
"ip": <ip>,
"parent": <parent>,
"type": ESXi Host
----
+

NOTE: 下一步使用计算资产记录中的 " 父 " 和 " ID " 字段引用要更新的记录。

. 配置特定计算节点资产：
+
.. 单击 * 放置 /assets/ ｛ asset_id ｝ /compute-nodes/｛ compute_id ｝ * 。
+
以下是 UI 中 API 的直接链接：

+
[listing]
----
https://<ManagementNodeIP>/mnode/#/assets/routes.v1.assets_api.put_assets_compute_id
----
.. 单击 * 试用 * 。
.. 输入带有父级信息的 "asset_id" 。
.. 输入带有 "id" 信息的 "compute_id" 。
.. 修改用户界面中的请求正文，以便仅更新计算资产记录中的密码和用户名参数：
+
[listing]
----
{
"password": "<password>",
"username": "<username>"
}
----
.. 单击 * 执行 * 。
.. 验证响应是否为 HTTP 200 ，表示新凭据已存储在引用的计算资产记录中


. 对需要使用新密码更新的其他计算节点资产重复上述两个步骤。
. 导航到 https://<mNode_ip>/inventory/1/[]。
+
.. 单击 * 授权 * 或任何锁定图标并完成以下操作：
+
... 输入 NetApp SolidFire 集群管理用户名和密码。
... 输入客户端 ID `mnode-client` 。
... 单击 * 授权 * 开始会话。
... 关闭窗口。


.. 在 REST API UI 中，单击 * 获取 /installations * 。
.. 单击 * 试用 * 。
.. 从刷新问题描述下拉列表中选择 * 对 * 。
.. 单击 * 执行 * 。
.. 验证响应是否为 HTTP 200 。


. 等待大约 15 分钟， vCenter 中的帐户锁定消息才会消失。




== 了解更多信息

* https://docs.netapp.com/us-en/vcp/index.html["适用于 vCenter Server 的 NetApp Element 插件"^]

