---
sidebar: sidebar 
permalink: docs/task_nde_access_dhcp.html 
summary: 了解如何在使用 DHCP 分配 IP 地址的环境中访问 NetApp 部署引擎。 
keywords: netapp, hci, netapp deployment engine, deployment, engine, deploy, access, dhcp 
---
= 在使用 DHCP 的环境中访问 NetApp 部署引擎
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在服务器自动从 DHCP 获取 IPv4 配置的环境中，您可以使用分配给其中一个存储节点上的绑定 1G 接口的 IPv4 地址来访问 NetApp 部署引擎。您可以使用 U 盘从其中一个存储节点检索 IPv4 地址。NetApp 部署引擎将自动发现使用 DHCP 分配的 IPv4 地址的其他计算和存储节点。除非您的网络有特殊要求，否则不应使用此方法。

.您需要的内容
* 您或您的网络管理员已完成安装和设置说明文档中的任务。
* 您可以对 NetApp HCI 节点进行物理访问。
* 所有 NetApp HCI 节点均已启动。
* 已在 NetApp HCI 管理和存储网络上启用 DHCP 。
* DHCP 地址池足够大，可以为每个 NetApp HCI 节点容纳两个 IPv4 地址。



NOTE: 要成功部署 NetApp HCI ，部署中的所有节点必须具有 DHCP 获取的或自动配置的 IPv4 地址（不能混用 IPv4 地址分配方法）。

.关于此任务
如果 DHCP 仅用于存储网络（绑定 10G 接口），则应使用链接中所述的步骤： link:task_nde_access_no_dhcp.html["在不使用 DHCP 的环境中访问 NetApp 部署引擎"] 以访问 NetApp 部署引擎。

.步骤
. 等待几分钟，以便节点请求 IP 地址。
. 选择一个存储节点，然后将 USB 记忆棒插入此节点。将其保留至少五秒钟。
. 卸下 USB 记忆棒，然后将其插入计算机。
. 打开 `reADME.html` 文件。此时将转到 NetApp 部署引擎用户界面。


[discrete]
== 了解更多信息

* link:firmware_driver_versions.html["NetApp HCI 支持的固件和ESXi驱动程序版本以及NetApp HCI 存储节点的固件版本"]

