---
sidebar: sidebar 
permalink: docs/task_hcc_upgrade_element_software.html 
summary: 在 NetApp HCI 系统升级过程中，您可以升级 NetApp Element 软件。 
keywords: netapp, hci, HealthTools, cluster, element, H610S upgrade, hcc 
---
= 升级 Element 软件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
要升级 NetApp Element 软件，您可以使用 NetApp 混合云控制 UI ， REST API 或 HealthTools 工具套件。Element 软件升级期间会禁止某些操作，例如添加和删除节点，添加和删除驱动器以及与启动程序，卷访问组和虚拟网络等关联的命令。

.您需要的内容
* * 管理员权限 * ：您拥有执行升级的存储集群管理员权限。
* * 有效升级路径 * ：您已检查要升级到的 Element 版本的升级路径信息并验证升级路径是否有效。https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_is_the_upgrade_matrix_for_storage_clusters_running_NetApp_Element_software%3F["NetApp 知识库：运行 NetApp Element 软件的存储集群的升级表"^]
* * 系统时间同步 * ：您已确保所有节点上的系统时间均已同步，并且已为存储集群和节点正确配置 NTP 。必须在每个节点 Web UI （`https://[IP address] ： 442` ）中为每个节点配置一个 DNS 命名服务器，并且不会出现与时间偏差相关的未解决集群故障。
* * 系统端口 * ：如果您使用 NetApp Hybrid Cloud Control 进行升级，则已确保必要的端口处于打开状态。请参见 link:hci_prereqs_required_network_ports.html["网络端口"] 有关详细信息 ...
* * 管理节点 * ：对于 NetApp Hybrid Cloud Control UI 和 API ，您环境中的管理节点运行的是 11.3 版。
* * 管理服务 * ：您已将管理服务捆绑包更新到最新版本。



IMPORTANT: 在将 Element 软件升级到 12.3.x 之前，您必须升级到最新的管理服务包如果要将 Element 软件更新到 12.3.x 版，则需要使用管理服务 2.14.60 或更高版本才能继续。

* * 集群运行状况 * ：您已验证集群是否已做好升级准备。请参见 link:task_hcc_upgrade_element_prechecks.html["在升级存储之前，请运行 Element 存储运行状况检查"]。
* * 已更新 H610S 节点的 BMC * ：您已升级 H610S 节点的 BMC 版本。请参见 link:rn_H610S_BMC_3.84.07.html["发行说明和升级说明"]。
* *最终用户许可协议(EULA)*：从管理服务2.20.69开始、您必须先接受并保存此EULA、然后才能使用NetApp Hybrid Cloud Control UI或API升级Element软件：
+
.. 在Web浏览器中打开管理节点的IP地址：
+
[listing]
----
https://<ManagementNodeIP>
----
.. 通过提供存储集群管理员凭据登录到 NetApp Hybrid Cloud Control 。
.. 选择靠近接口右上角的 * 升级 * 。
.. 此时将弹出EULA。向下滚动、选择*我接受当前更新和所有未来更新*、然后选择*保存*。




.升级选项
选择以下 Element 软件升级选项之一：

* <<使用 NetApp Hybrid Cloud Control UI 升级 Element 存储>>
* <<使用 NetApp Hybrid Cloud Control API 升级 Element 存储>>
* <<使用 HealthTools 升级已连接站点上的 Element 软件>>
* <<使用 HealthTools 升级非公开站点上的 Element 软件>>



IMPORTANT: 如果您要将 H610S 系列节点升级到 Element 12.3.x ，并且此节点运行的 Element 版本早于 11.8 ，则需要执行其他升级步骤（<<将 H610S 存储节点升级到 Element 12.3.x （第 2 阶段）,第 2 阶段>>）。如果您运行的是 Element 11.8 或更高版本，则不需要执行其他升级步骤（第 2 阶段）。



== 使用 NetApp Hybrid Cloud Control UI 升级 Element 存储

您可以使用 NetApp Hybrid Cloud Control UI 升级存储集群。


CAUTION: 有关使用 NetApp Hybrid Cloud Control 升级存储集群时的潜在问题及其解决方法，请参见 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Potential_issues_and_workarounds_when_running_storage_upgrades_using_NetApp_Hybrid_Cloud_Control["知识库文章"^]。


TIP: 对于非 H610S 平台，每个节点的升级过程大约需要 30 分钟。

.步骤
. 在Web浏览器中打开管理节点的IP地址：
+
[listing]
----
https://<ManagementNodeIP>
----
. 通过提供存储集群管理员凭据登录到 NetApp Hybrid Cloud Control 。
. 选择靠近接口右上角的 * 升级 * 。
. 在 * 升级 * 页面上，选择 * 存储 * 。
+
* 存储 * 选项卡列出了安装过程中的存储集群。如果 NetApp Hybrid Cloud Control 无法访问某个集群，则该集群将不会显示在 * 升级 * 页面上。

. 从以下选项中进行选择，并执行一组适用于您的集群的步骤：
+
[cols="2*"]
|===
| 选项 | 步骤 


| 运行Element 11.8及更高版本的所有集群  a| 
.. 选择 * 浏览 * 上传您下载的升级软件包。
.. 等待上传完成。进度条会显示上传状态。
+

CAUTION: 如果您离开浏览器窗口，则文件上传将丢失。

+
成功上传并验证文件后，将显示一条屏幕消息。验证可能需要几分钟时间。如果在此阶段离开浏览器窗口，则会保留文件上传。

.. 选择 * 开始升级 * 。
+

TIP: 升级期间， * 升级状态 * 会发生更改，以反映此过程的状态。它也会根据您执行的操作而发生更改，例如暂停升级或升级返回错误。请参见 <<升级状态更改>>。

+

NOTE: 在升级过程中，您可以退出此页面，稍后再返回此页面以继续监控进度。如果集群行已折叠，则此页面不会动态更新状态和当前版本。必须展开集群行才能更新此表，您也可以刷新此页面。

+
升级完成后，您可以下载日志。





| 您要升级运行的 Element 版本早于 11.8 的 H610S 集群。  a| 
.. 选择要升级的集群旁边的下拉箭头，然后从可用的升级版本中进行选择。
.. 选择 * 开始升级 * 。升级完成后， UI 将提示您执行此过程的第 2 阶段。
.. 完成中所需的其他步骤（第 2 阶段） https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["知识库文章"^]，并在用户界面中确认您已完成第 2 阶段。


升级完成后，您可以下载日志。有关各种升级状态更改的信息，请参见 <<升级状态更改>>。

|===




=== 升级状态更改

以下是用户界面中的 * 升级状态 * 列在升级过程之前，期间和之后显示的不同状态：

[cols="2*"]
|===
| 升级状态 | Description 


| 最新 | 集群已升级到最新可用的 Element 版本。 


| 可用版本 | 可以升级较新版本的 Element 和 / 或存储固件。 


| 正在进行中 | 正在升级。进度条会显示升级状态。屏幕上的消息还会显示节点级别的故障，并在升级过程中显示集群中每个节点的节点 ID 。您可以使用 Element UI 或适用于 vCenter Server 的 NetApp Element 插件 UI 监控每个节点的状态。 


| 升级暂停 | 您可以选择暂停升级。根据升级过程的状态，暂停操作可能会成功或失败。您将看到一个 UI 提示，要求您确认暂停操作。要确保集群在暂停升级之前处于安全位置，可能需要长达两个小时才能完全暂停升级操作。要恢复升级，请选择 * 恢复 * 。 


| 已暂停 | 您已暂停升级。选择 * 恢复 * 以恢复此过程。 


| error | 升级期间发生错误。您可以下载错误日志并将其发送给 NetApp 支持部门。解决此错误后，您可以返回到页面并选择 * 恢复 * 。恢复升级时，进度条会后退几分钟，而系统会运行运行状况检查并检查升级的当前状态。 


| 完成并进行跟进 | 仅适用于从早于 118 的 Element 版本升级的 H610S 节点。升级过程的第 1 阶段完成后，此状态将提示您执行升级的第 2 阶段（请参见 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["知识库文章"^]）。完成第 2 阶段并确认已完成后，状态将变为 * 最新 * 。 
|===


== 使用 NetApp Hybrid Cloud Control API 升级 Element 存储

您可以使用 API 将集群中的存储节点升级到最新的 Element 软件版本。您可以使用自己选择的自动化工具来运行 API 。此处介绍的 API 工作流使用管理节点上提供的 REST API UI 作为示例。

.步骤
. 将存储升级软件包下载到可供管理节点访问的设备；转到 NetApp HCI 软件 https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab["下载页面"^] 并下载最新的存储节点映像。
. 将存储升级软件包上传到管理节点：
+
.. 在管理节点上打开管理节点 REST API UI ：
+
[listing]
----
https://<ManagementNodeIP>/package-repository/1/
----
.. 选择 * 授权 * 并完成以下操作：
+
... 输入集群用户名和密码。
... 输入客户端 ID `mnode-client` 。
... 选择 * 授权 * 以开始会话。
... 关闭授权窗口。


.. 从 REST API UI 中，选择 * POST /packages* 。
.. 选择 * 试用 * 。
.. 选择 * 浏览 * 并选择升级软件包。
.. 选择 * 执行 * 以启动上传。
.. 在响应中，复制并保存软件包 ID （` "id"` ）以供后续步骤使用。


. 验证上传状态。
+
.. 从 REST API UI 中，选择 * GET​ /v í packages​ / ｛ id ｝​ /status* 。
.. 选择 * 试用 * 。
.. 在 * id * 中输入上一步复制的软件包 ID 。
.. 选择 * 执行 * 以启动状态请求。
+
完成后，此响应会将 `state` 指示为 `Success` 。



. 找到存储集群 ID ：
+
.. 在管理节点上打开管理节点 REST API UI ：
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. 选择 * 授权 * 并完成以下操作：
+
... 输入集群用户名和密码。
... 输入客户端 ID `mnode-client` 。
... 选择 * 授权 * 以开始会话。
... 关闭授权窗口。


.. 从 REST API UI 中，选择 * 获取 /installations * 。
.. 选择 * 试用 * 。
.. 选择 * 执行 * 。
.. 从响应中复制安装资产 ID （` "id"` ）。
.. 从 REST API UI 中，选择 * 获取 /installations/ ｛ id ｝ * 。
.. 选择 * 试用 * 。
.. 将安装资产 ID 粘贴到 * id * 字段中。
.. 选择 * 执行 * 。
.. 在此响应中，复制并保存要升级的集群的存储集群 ID （` "id"` ），以便日后使用。


. 运行存储升级：
+
.. 在管理节点上打开存储 REST API UI ：
+
[listing]
----
https://<ManagementNodeIP>/storage/1/
----
.. 选择 * 授权 * 并完成以下操作：
+
... 输入集群用户名和密码。
... 输入客户端 ID `mnode-client` 。
... 选择 * 授权 * 以开始会话。
... 关闭授权窗口。


.. 选择 * POST /upgrades* 。
.. 选择 * 试用 * 。
.. 在参数字段中输入升级软件包 ID 。
.. 在参数字段中输入存储集群 ID 。
+
有效负载应类似于以下示例：

+
[listing]
----
{
  "config": {},
  "packageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4",
  "storageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4"
}
----
.. 选择 * 执行 * 以启动升级。
+
响应应指示状态为 `initializing` ：

+
[listing]
----
{
  "_links": {
    "collection": "https://localhost:442/storage/upgrades",
    "self": "https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1",
    "log": https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1/log
  },
  "storageId": "114f14a4-1a1a-11e9-9088-6c0b84e200b4",
  "upgradeId": "334f14a4-1a1a-11e9-1055`-6c0b84e2001b4",
  "packageId": "774f14a4-1a1a-11e9-8888-6c0b84e200b4",
  "config": {},
  "state": "initializing",
  "status": {
    "availableActions": [
      "string"
    ],
    "message": "string",
    "nodeDetails": [
      {
        "message": "string",
        "step": "NodePreStart",
        "nodeID": 0,
        "numAttempt": 0
      }
    ],
    "percent": 0,
    "step": "ClusterPreStart",
    "timestamp": "2020-04-21T22:10:57.057Z",
    "failedHealthChecks": [
      {
        "checkID": 0,
        "name": "string",
        "displayName": "string",
        "passed": true,
        "kb": "string",
        "description": "string",
        "remedy": "string",
        "severity": "string",
        "data": {},
        "nodeID": 0
      }
    ]
  },
  "taskId": "123f14a4-1a1a-11e9-7777-6c0b84e123b2",
  "dateCompleted": "2020-04-21T22:10:57.057Z",
  "dateCreated": "2020-04-21T22:10:57.057Z"
}
----
.. 复制响应中的升级 ID （` "upgradeId"` ）。


. 验证升级进度和结果：
+
.. 选择 * 获取​ /upgrades/｛ upgradeId ｝ * 。
.. 选择 * 试用 * 。
.. 在 * 升级 Id* 中输入上一步中的升级 ID 。
.. 选择 * 执行 * 。
.. 如果在升级期间出现问题或存在特殊要求，请执行以下操作之一：
+
[cols="2*"]
|===
| 选项 | 步骤 


| 您需要更正响应正文中出现的 `failedHealthChecks` 消息导致的集群运行状况问题。  a| 
... 转至为每个问题描述列出的特定知识库文章，或者执行指定的补救措施。
... 如果指定了 KB ，请完成相关知识库文章中所述的过程。
... 解决集群问题后，如果需要，请重新进行身份验证，然后选择 * PUT ​ /upgrades/｛ upgradeId ｝ * 。
... 选择 * 试用 * 。
... 在 * 升级 Id* 中输入上一步中的升级 ID 。
... 在请求正文中输入 ` action" ： "resume"` 。
+
[listing]
----
{
  "action": "resume"
}
----
... 选择 * 执行 * 。




| 由于维护窗口正在关闭或其他原因，您需要暂停升级。  a| 
... 如果需要，请重新进行身份验证并选择 * PUT ​ /upgrades/｛ upgradeId ｝ * 。
... 选择 * 试用 * 。
... 在 * 升级 Id* 中输入上一步中的升级 ID 。
... 在请求正文中输入 ` action" ： "pause"` 。
+
[listing]
----
{
  "action": "pause"
}
----
... 选择 * 执行 * 。




| 如果要升级运行的 Element 版本早于 11.8 的 H610S 集群，则会在响应正文中看到状态 `finishedNeedsAck` 。您需要对每个 H610S 存储节点执行其他升级步骤（第 2 阶段）。  a| 
... 请参见 <<Upgrading H610S storage nodes to Element 12.3.x or later (phase 2)>> 并完成每个节点的过程。
... 如果需要，请重新进行身份验证并选择 * PUT ​ /upgrades/｛ upgradeId ｝ * 。
... 选择 * 试用 * 。
... 在 * 升级 Id* 中输入上一步中的升级 ID 。
... 在请求正文中输入 ` action" ： "acknowledge "` 。
+
[listing]
----
{
  "action": "acknowledge"
}
----
... 选择 * 执行 * 。


|===
.. 根据需要多次运行 * 获取​ /upgrades/｛ upgradeId ｝ * API ，直到此过程完成。
+
在升级期间，如果未遇到任何错误，则 `stStatus` 会指示 `Running` 。升级每个节点后， `step` 值将更改为 `NodeFinished` 。

+
当 `Percent` 值为 `100` 且 `state` 指示 `finished` 时，升级已成功完成。







== 使用 NetApp Hybrid Cloud Control 升级失败时会发生什么情况

如果驱动器或节点在升级期间发生故障， Element UI 将显示集群故障。升级过程不会继续到下一个节点，而是等待集群故障解决。UI 中的进度条显示升级正在等待集群故障解决。在此阶段，在 UI 中选择 * 暂停 * 将不起作用，因为升级会等待集群运行正常。您需要联系 NetApp 支持部门以协助进行故障调查。

NetApp Hybrid Cloud Control 具有预先设置的三小时等待时间，在此期间可能会发生以下情况之一：

* 集群故障将在三小时内得到解决，升级将继续进行。在这种情况下，您无需执行任何操作。
* 此问题在三小时后仍然存在，并且升级状态显示 * 错误 * 并显示红色横幅。解决问题后，您可以通过选择 * 恢复 * 来恢复升级。
* NetApp 支持部门已确定需要暂时中止升级，以便在三小时内采取更正措施。支持人员将使用 API 中止升级。



CAUTION: 在更新节点时中止集群升级可能会导致驱动器异常地从节点中删除。如果驱动器被异常删除，则在升级期间重新添加驱动器需要 NetApp 支持部门手动干预。节点执行固件更新或更新后同步活动可能需要较长时间。如果升级进度似乎停滞，请联系 NetApp 支持部门以获得帮助。



== 使用 HealthTools 升级已连接站点上的 Element 软件

.步骤
. 下载存储升级软件包；转到 NetApp HCI 软件 https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab["下载页面"^] 并将最新的存储节点映像下载到非管理节点设备。
+

NOTE: 要升级 Element 存储软件，您需要最新版本的 HealthTools 。

. 将 ISO 文件复制到可访问位置（如 /tmp ）的管理节点。
+
上传 ISO 文件时，请确保文件名不会更改，否则后续步骤将失败。

. * 可选 * ：在升级之前，将 ISO 从管理节点下载到集群节点。
+
此步骤可在存储节点上预暂存 ISO 并运行额外的内部检查以确保集群处于可升级的良好状态，从而缩短升级时间。执行此操作不会将集群置于 " 升级 " 模式或限制任何集群操作。

+
[listing]
----
sfinstall <MVIP> -u <cluster_username> <path-toinstall-file-ISO> --stage
----
+

NOTE: 在命令行中省略密码，以允许 `sfinstall` 提示输入信息。对于包含特殊字符的密码，请在每个特殊字符之前添加反斜杠（` \` ）。例如， `mypass ！@1` 应输入为 `mypass\ ！ \@` 。

+
* 示例 * 请参见以下示例输入：

+
[listing]
----
sfinstall 10.117.0.244 -u admin /tmp/solidfire-rtfisodium-11.0.0.345.iso --stage
----
+
此示例的输出显示， `sfinstall` 尝试验证是否提供了更高版本的 `sfinstall` ：

+
[listing]
----
sfinstall 10.117.0.244 -u admin
/tmp/solidfire-rtfisodium-11.0.0.345.iso 2018-10-01 16:52:15:
Newer version of sfinstall available.
This version: 2018.09.01.130, latest version: 2018.06.05.901.
The latest version of the HealthTools can be downloaded from:
https:// mysupport.netapp.com/NOW/cgi-bin/software/
or rerun with --skip-version-check
----
+
请参见以下成功预处理操作示例摘录：

+

NOTE: 暂存完成后，升级事件发生后，此消息将显示 `Storage Node Upgrade Staging Successful` 。

+
[listing]
----
flabv0004 ~ # sfinstall -u admin
10.117.0.87 solidfire-rtfi-sodium-patch3-11.3.0.14171.iso --stage
2019-04-03 13:19:58: sfinstall Release Version: 2019.01.01.49 Management Node Platform:
Ember Revision: 26b042c3e15a Build date: 2019-03-12 18:45
2019-04-03 13:19:58: Checking connectivity to MVIP 10.117.0.87
2019-04-03 13:19:58: Checking connectivity to node 10.117.0.86
2019-04-03 13:19:58: Checking connectivity to node 10.117.0.87
...
2019-04-03 13:19:58: Successfully connected to cluster and all nodes
...
2019-04-03 13:20:00: Do you want to continue? ['Yes', 'No']: Yes
...
2019-04-03 13:20:55: Staging install pack on cluster nodes
2019-04-03 13:20:55: newVersion: 11.3.0.14171
2019-04-03 13:21:01: nodeToStage: nlabp2814, nlabp2815, nlabp2816, nlabp2813
2019-04-03 13:21:02: Staging Node nlabp2815 mip=[10.117.0.87] nodeID=[2] (1 of 4 nodes)
2019-04-03 13:21:02: Node Upgrade serving image at
http://10.117.0.204/rtfi/solidfire-rtfisodium-
patch3-11.3.0.14171/filesystem.squashfs
...
2019-04-03 13:25:40: Staging finished. Repeat the upgrade command without the --stage option to start the upgrade.
----
+
升级完成后，暂存的 ISO 将被自动删除。但是，如果升级尚未启动且需要重新计划，则可以使用以下命令手动取消暂存 ISO ：

+
`sfinstall <MVIP> -u <cluster_username> -destage`

+
升级开始后，降级选项将不再可用。

. 使用 `sfinstall` 命令和 ISO 文件的路径开始升级：
+
`sfinstall <MVIP> -u <cluster_username> <path-toinstall-file-ISO>`

+
* 示例 *

+
请参见以下输入命令示例：

+
[listing]
----
sfinstall 10.117.0.244 -u admin /tmp/solidfire-rtfi-sodium-11.0.0.345.iso
----
+
此示例的输出显示， `sfinstall` 尝试验证是否提供了更高版本的 `sfinstall` ：

+
[listing]
----
sfinstall 10.117.0.244 -u admin /tmp/solidfire-rtfi-sodium-11.0.0.345.iso
2018-10-01 16:52:15: Newer version of sfinstall available.
This version: 2018.09.01.130, latest version: 2018.06.05.901.
The latest version of the HealthTools can be downloaded from:
https://mysupport.netapp.com/NOW/cgi-bin/software/ or rerun with --skip-version-check
----
+
请参见以下成功升级示例摘录。升级事件可用于监控升级进度。

+
[listing]
----
# sfinstall 10.117.0.161 -u admin solidfire-rtfi-sodium-11.0.0.761.iso
2018-10-11 18:28
Checking connectivity to MVIP 10.117.0.161
Checking connectivity to node 10.117.0.23
Checking connectivity to node 10.117.0.24
...
Successfully connected to cluster and all nodes
###################################################################
You are about to start a new upgrade
10.117.0.161
10.3.0.161
solidfire-rtfi-sodium-11.0.0.761.iso
Nodes:
10.117.0.23 nlabp1023 SF3010 10.3.0.161
10.117.0.24 nlabp1025 SF3010 10.3.0.161
10.117.0.26 nlabp1027 SF3010 10.3.0.161
10.117.0.28 nlabp1028 SF3010 10.3.0.161
###################################################################
Do you want to continue? ['Yes', 'No']: yes
...
Watching for new network faults. Existing fault IDs are set([]).
Checking for legacy network interface names that need renaming
Upgrading from 10.3.0.161 to 11.0.0.761 upgrade method=rtfi
Waiting 300 seconds for cluster faults to clear
Waiting for caches to fall below threshold
...
Installing mip=[10.117.0.23] nodeID=[1] (1 of 4 nodes)
Starting to move primaries.
Loading volume list
Moving primary slice=[7] away from mip[10.117.0.23] nodeID[1] ssid[11] to new ssid[15]
Moving primary slice=[12] away from mip[10.117.0.23] nodeID[1] ssid[11] to new ssid[15]
...
Installing mip=[10.117.114.24] nodeID=[2] (2 of 4 nodes)
Starting to move primaries.
Loading volume list
Moving primary slice=[5] away from mip[10.117.114.24] nodeID[2] ssid[7] to new ssid[11]
...
Install of solidfire-rtfi-sodium-11.0.0.761 complete.
Removing old software
No staged builds present on nodeID=[1]
No staged builds present on nodeID=[2]
...
Starting light cluster block service check
----



IMPORTANT: 如果您要将 H610S 系列节点升级到 Element 12.3.x ，并且此节点运行的 Element 版本早于 11.8 ，则需要执行其他升级步骤（<<将 H610S 存储节点升级到 Element 12.3.x （第 2 阶段）,第 2 阶段>>）。如果您运行的是 Element 11.8 或更高版本，则不需要执行其他升级步骤（第 2 阶段）。



== 使用 HealthTools 升级非公开站点上的 Element 软件

您可以使用 HealthTools 工具套件在没有外部连接的非公开站点上更新 NetApp Element 软件。

.您需要的内容
. 转到 NetApp HCI 软件 https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab["下载页面"^]。
. 选择正确的软件版本并将最新的存储节点映像下载到非管理节点计算机。
+

NOTE: 要升级 Element 存储软件，您需要最新版本的 HealthTools 。

. 下载此 https://library.netapp.com/ecm/ecm_get_file/ECMLP2840740["JSON 文件"^] 从 NetApp 支持站点的非管理节点计算机上，将其重命名为 `metadata 。 json` 。
. 将此 ISO 文件复制到管理节点中可访问的位置，例如 ` /tmp` 。
+

TIP: 例如，您可以使用 SCP 来执行此操作。上传 ISO 文件时，请确保文件名不会更改，否则后续步骤将失败。



.步骤
. 运行 `sfupdate-healthtools` 命令：
+
[listing]
----
sfupdate-healthtools <path-to-healthtools-package>
----
. 检查安装的版本：
+
[listing]
----
sfupdate-healthtools -v
----
. 根据元数据 JSON 文件检查最新版本：
+
[listing]
----
sfupdate-healthtools -l --metadata=<path-to-metadata-json>
----
. 确保集群已准备就绪：
+
[listing]
----
sudo sfupgradecheck -u <cluster_username> -p <cluster_password> MVIP --metadata=<path-to-metadata-json>
----
. 使用 ISO 文件和元数据 JSON 文件的路径运行 `sfinstall` 命令：
+
[listing]
----
sfinstall -u <cluster_username> <MVIP> <path-toinstall-file-ISO> --metadata=<path-to-metadata-json-file>
----
+
请参见以下输入命令示例：

+
[listing]
----
sfinstall -u admin 10.117.78.244 /tmp/solidfire-rtfi-11.3.0.345.iso --metadata=/tmp/metadata.json
----
+
* 可选 * 您可以将 ` -stage` 标志添加到 `sfinstall` 命令中，以便预先暂存升级。




IMPORTANT: 如果您要将 H610S 系列节点升级到 Element 12.3.x ，并且此节点运行的 Element 版本早于 11.8 ，则需要执行其他升级步骤（<<将 H610S 存储节点升级到 Element 12.3.x （第 2 阶段）,第 2 阶段>>）。如果您运行的是 Element 11.8 或更高版本，则不需要执行其他升级步骤（第 2 阶段）。



== 使用 HealthTools 升级失败时会发生什么情况

如果软件升级失败，您可以暂停升级。


TIP: 只能使用 Ctrl-C 暂停升级这样，系统就可以自行清理。

当 `sfinstall` 等待集群故障清除时，如果任何故障导致故障仍然存在，则 `sfinstall` 不会继续到下一个节点。

.步骤
. 您应使用 Ctrl+C 停止 `sfinstall`
. 请联系 NetApp 支持部门以协助进行故障调查。
. 使用相同的 `sfinstall` 命令恢复升级。
. 使用 Ctrl+C 暂停升级时，如果升级当前正在升级节点，请选择以下选项之一：
+
** * 等待 * ：允许当前升级节点完成，然后再重置集群常量。
** * 继续 * ：继续升级，此操作将取消暂停。
** * 中止 * ：重置集群常量并立即中止升级。
+

NOTE: 在更新节点时中止集群升级可能会导致驱动器异常地从节点中删除。如果驱动器被异常删除，则在升级期间重新添加驱动器需要 NetApp 支持部门手动干预。节点执行固件更新或更新后同步活动可能需要较长时间。如果升级进度似乎停滞，请联系 NetApp 支持部门以获得帮助。







== 将 H610S 存储节点升级到 Element 12.3.x （第 2 阶段）

如果您要将 H610S 系列节点升级到 Element 12.3.x ，而该节点运行的 Element 版本早于 11.8 ，则升级过程将包括两个阶段。

首先执行的第 1 阶段与标准升级到 Element 12.3.x 的过程相同。它会以滚动方式在集群中逐个节点安装 Element 软件和所有 5 个固件更新。由于固件有效负载，每个 H610S 节点的此过程预计大约需要 1.5 到 2 小时，包括在升级结束时为每个节点执行一个冷启动周期。

第 2 阶段涉及完成所需步骤，以便对每个 H610S 节点执行完全关闭节点和断开电源的操作 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["知识库"^]。此阶段预计每个 H610S 节点大约需要一小时。


IMPORTANT: 完成第 1 阶段后，五个固件更新中的四个将在每个 H610S 节点的冷启动期间激活；但是，复杂可编程逻辑设备（ CPLD ）固件需要完全断开电源并重新连接才能完全安装。CPLD 固件更新可防止在未来重新启动或重新启动期间发生 NVDIMM 故障和元数据驱动器逐出。此电源重置预计每个 H610S 节点大约需要一小时。它需要关闭节点，拔下电源线或通过智能 PDU 断开电源，等待大约 3 分钟，然后重新连接电源。

.开始之前
* 您已完成 H610S 升级过程的第 1 阶段，并已使用一个标准 Element 存储升级过程升级存储节点。



NOTE: 第 2 阶段需要现场人员。

.步骤
. （第 2 阶段）完成集群中每个 H610S 节点所需的电源重置过程：



NOTE: 如果集群还具有非 H610S 节点，则这些非 H610S 节点将免于进入第 2 阶段，无需关闭或断开其电源。

. 请联系 NetApp 支持部门以获得帮助并计划此升级。
. 按照此步骤中的第 2 阶段升级操作步骤进行操作 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["知识库"^] 完成每个 H610S 节点的升级所需的时间。


[discrete]
== 了解更多信息

* https://docs.netapp.com/us-en/vcp/index.html["适用于 vCenter Server 的 NetApp Element 插件"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI 资源页面"^]

