---
sidebar: sidebar 
permalink: docs/task_hcc_upgrade_compute_firmware_ansible.html 
summary: 对于 H 系列计算节点， NetApp 提供了 Ansible 角色，可帮助您自动对 BMC ， BIOS 和 NIC 等硬件组件进行固件升级。 
keywords: netapp, hci, on premise, cluster, element, compute node, ansible upgrade, upgrade role 
---
= 利用 Ansible 自动升级计算节点固件
:allow-uri-read: 


[role="lead"]
您可以使用 NetApp 混合云控制中的工作流更新 NetApp HCI 计算节点上的系统固件，包括 BMC ， BIOS 和 NIC 等组件的固件。对于具有大型计算集群的安装，您可以使用 Ansible 对整个集群执行滚动升级，从而自动执行工作流。


NOTE: 虽然 NetApp 提供了自动化计算节点固件升级的 Ansible 角色，但自动化是一个辅助组件，需要额外的设置和软件组件才能运行。只有在尽力而为的情况下，才支持修改 Ansible 自动化。


NOTE: 用于升级的 Ansible 角色仅适用于 NetApp HCI H 系列计算节点。您不能使用此角色升级第三方计算节点。

.您需要什么？ #8217 ；将需要什么
* * 固件升级的准备情况和前提条件 * ：您的 NetApp HCI 安装必须准备好进行固件升级，如的说明所述 link:task_hcc_upgrade_compute_node_firmware.html["正在执行固件升级"^]。
* * 准备在 Ansible 控制节点上运行自动化 * ：在 Ansible 中运行固件更新自动化的物理或虚拟服务器。


在生产环境中，您应以滚动方式更新 NetApp HCI 安装中集群中的计算节点；一个节点一个节点，一个节点一个节点。NetApp Hybrid Cloud Control 中的 API 可为单个计算节点编排整体计算节点固件升级过程，包括运行运行状况检查，将计算节点上的 ESXi 置于维护状态以及重新启动计算节点以应用固件升级。Ansible 角色提供了一个选项，用于为一组计算节点或整个集群编排固件升级。

要开始使用，请导航到 https://github.com/NetApp-Automation/nar_compute_firmware_upgrade["GitHub 上的 NetApp Ansible 存储库"^] 并下载 `NAR_compute_nodes_firmware_upgrades` 角色和文档。

[discrete]
== 了解更多信息

* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI 资源页面"^]

